
name: Main Branch Static Analysis Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        working-directory: ./headapps/nextjs-starter
        run: pnpm install

      - name: Build project
        working-directory: ./headapps/nextjs-starter
        run: pnpm run build

       
  pipeline_scan:
    needs: build
    runs-on: ubuntu-latest
    name: Pipeline Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package source code for Veracode
        run: |
          mkdir veracode-package
          cp -r headapps/nextjs-starter/* veracode-package/
          zip -r veracode-package.zip veracode-package

          #  Submit  project to pipeline scan
      - name: Pipeline Scan
        run: |
           curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
           unzip -o pipeline-scan-LATEST.zip
           java -jar pipeline-scan.jar --veracode_api_id="${{secrets.VERACODE_API_ID}}" --veracode_api_key="${{secrets.VERACODE_API_KEY}}" --fail_on_severity="Very High, High" --file="veracode-package.zip" --app_id="${{secrets.VERACODE_APP_ID}}" --json_output_file="results.json" || true

      - uses: actions/upload-artifact@v4
        with:
          name: ScanResults
          path: results.json
        
  # Convert pipeline scan output to SARIF format  
  process-results:
    needs: pipeline_scan
    runs-on: ubuntu-latest
    steps:

    - name: Retrieve results
      uses: actions/download-artifact@v4
      with:
        name: ScanResults
        path: .
        
    - name: Convert Veracode JSON to SARIF
      uses: veracode/veracode-pipeline-scan-results-to-sarif@master
      with:
        pipeline-results-json: results.json
        output-results-sarif: veracode-results.sarif
        scan-type: pipeline
        githubToken: ${{ secrets.GITHUB_TOKEN }} # uses token with correct permission
        

    - name: Upload SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: veracode-results.sarif



    - name: Upload SARIF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SarifResults
        path: veracode-results.sarif


        
