
name: Combined Veracode Scans


on:
  push:
  pull_request:
  workflow_dispatch:


permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        working-directory: ./headapps/nextjs-starter
        run: pnpm install

      - name: Build Next.js project
        working-directory: ./headapps/nextjs-starter
        run: pnpm run build

      - name: Package source code for Veracode
        run: |
         mkdir veracode-package
         rsync -av --progress headapps/nextjs-starter/ veracode-package \
          --exclude node_modules \
          --exclude .next \
          --exclude .git \
          --exclude .vercel \
          --exclude coverage \
          --exclude '*.log'
         zip -r veracode-package.zip veracode-package

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: veracode-package
          path: veracode-package.zip

  pipeline_scan:
    needs: build
    name: pipeline_scan
    runs-on: ubuntu-latest
    steps:
      - name: Download packaged artifact
        uses: actions/download-artifact@v4
        with:
          name: veracode-package
          path: .

      - name: Pipeline Scan (Fail on Default/main Branch)
        if: github.ref_name == github.event.repository.default_branch || github.base_ref == github.event.repository.default_branch
        run: |
          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -o pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar \
            --veracode_api_id="${{ secrets.VERACODE_API_ID }}" \
            --veracode_api_key="${{ secrets.VERACODE_API_KEY }}" \
            --file="veracode-package.zip" \
            --app_id="${{ secrets.VERACODE_APP_ID }}" \
            --json_output_file="results.json" || true

      - name: Pipeline Scan (Other Branches)
        if: github.ref_name != github.event.repository.default_branch && github.base_ref != github.event.repository.default_branch
        run: |
          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -o pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar \
            --veracode_api_id="${{ secrets.VERACODE_API_ID }}" \
            --veracode_api_key="${{ secrets.VERACODE_API_KEY }}" \
            --file="veracode-package.zip" \
            --app_id="${{ secrets.VERACODE_APP_ID }}" \
            --json_output_file="results.json" || true

      - uses: actions/upload-artifact@v4
        with:
          name: pipeline-results
          path: results.json
          
  #createprofile: true -> this needs to changed to false
  sandbox_scan:
    needs: build
    name: sandbox_scan
    runs-on: ubuntu-latest
    if: github.ref_name != github.event.repository.default_branch && github.base_ref != github.event.repository.default_branch
    steps:
      - name: Download packaged artifact
        uses: actions/download-artifact@v4
        with:
          name: veracode-package
          path: .

      - name: Sandbox Scan (Non-blocking on all branches except default/main)
        uses: veracode/veracode-uploadandscan-action@0.2.11
        with:
          appname: '${{ secrets.VERACODE_APP_NAME }}'
          filepath: 'veracode-package.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          sandboxname: 'GitHubActions'
          createsandbox: true
          createprofile: true
          failbuild: false
          maxretrycount: 10
          
  #createprofile: true -> this needs to changed to false
  policy_scan:
    needs: build
    name: policy_scan
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch || github.base_ref == github.event.repository.default_branch
    steps:
      - name: Download packaged artifact
        uses: actions/download-artifact@v4
        with:
          name: veracode-package
          path: .

      - name: Policy Scan (Blocking on default/main branch)
        uses: veracode/veracode-uploadandscan-action@0.2.11
        with:
          appname: '${{ secrets.VERACODE_APP_NAME }}'
          filepath: 'veracode-package.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          createprofile: true
          failbuild: true
          maxretrycount: 10
